#!/usr/bin/env python3
"""Legacy v1 payload encoder retained for compatibility and protocol inspection."""

from __future__ import annotations

import argparse
import ipaddress
import lzma
import os
import re
import sys
from pathlib import Path

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError as exc:
    raise SystemExit(
        "Missing dependency 'cryptography'. Run: python -m pip install -r requirements.txt"
    ) from exc

MAGIC = b"LIL1"
NONCE_SIZE = 12
AAD = b"LiLoaden:AES-GCM:LZMA:IPv6:v1"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Encrypt a binary file with AES-GCM, compress it with LZMA, and generate a C++ header.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        epilog="Example: %(prog)s input.bin payload.h --key-file aes.key",
    )
    parser.add_argument("input", type=Path, metavar="INPUT", help="binary input file")
    parser.add_argument("output", type=Path, metavar="OUTPUT_HEADER", help="generated C++ header path")
    keys = parser.add_mutually_exclusive_group(required=True)
    keys.add_argument("--key-hex", metavar="HEX", help="AES key as exactly 32, 48, or 64 hexadecimal characters")
    keys.add_argument(
        "--key-file", type=Path, metavar="FILE", help="file containing exactly 16, 24, or 32 raw AES key bytes"
    )
    parser.add_argument(
        "--namespace",
        default="liloaden_payload",
        metavar="CXX_NAMESPACE",
        help="C++ namespace for generated constants; nested names such as foo::bar are accepted",
    )
    return parser.parse_args()


def read_key(args: argparse.Namespace) -> bytes:
    if args.key_hex is not None:
        try:
            key = bytes.fromhex(args.key_hex)
        except ValueError as exc:
            raise ValueError("--key-hex must be a valid hexadecimal string") from exc
    else:
        key = args.key_file.read_bytes()
    if len(key) not in (16, 24, 32):
        raise ValueError("the AES key must contain exactly 16, 24, or 32 bytes")
    return key


def validate_namespace(namespace: str) -> None:
    identifier = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
    if not all(identifier.fullmatch(part) for part in namespace.split("::")):
        raise ValueError("--namespace must be a valid C++ namespace, for example foo or foo::bar")


def encode_payload(plaintext: bytes, key: bytes) -> bytes:
    nonce = os.urandom(NONCE_SIZE)
    # AESGCM.encrypt appends the 16-byte authentication tag to the ciphertext.
    encrypted = AESGCM(key).encrypt(nonce, plaintext, AAD)
    envelope = MAGIC + bytes((len(key),)) + nonce + encrypted
    return lzma.compress(envelope, format=lzma.FORMAT_XZ)


def to_ipv6(compressed: bytes) -> list[str]:
    padded = compressed + b"\0" * ((-len(compressed)) % 16)
    return [
        ipaddress.IPv6Address(padded[offset : offset + 16]).exploded
        for offset in range(0, len(padded), 16)
    ]


def verify(addresses: list[str], compressed_size: int, key: bytes, expected: bytes) -> None:
    encoded = b"".join(ipaddress.IPv6Address(item).packed for item in addresses)
    envelope = lzma.decompress(encoded[:compressed_size], format=lzma.FORMAT_XZ)
    if envelope[:4] != MAGIC or envelope[4] != len(key):
        raise RuntimeError("internal verification failed: invalid envelope header")
    nonce = envelope[5 : 5 + NONCE_SIZE]
    actual = AESGCM(key).decrypt(nonce, envelope[5 + NONCE_SIZE :], AAD)
    if actual != expected:
        raise RuntimeError("internal verification failed: restored data differs from input")


def render_header(
    source: Path,
    namespace: str,
    addresses: list[str],
    compressed_size: int,
    original_size: int,
    key_bits: int,
) -> str:
    values = "\n".join(f'    "{address}",' for address in addresses)
    return f"""// Generated by legacy_payload_encoder.py from {source.name}. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace {namespace} {{

inline constexpr std::string_view kCipher = "AES-{key_bits}-GCM";
inline constexpr std::string_view kCompression = "LZMA/XZ";
inline constexpr std::size_t kOriginalSize = {original_size};
inline constexpr std::size_t kCompressedSize = {compressed_size};
inline constexpr std::array<std::string_view, {len(addresses)}> kIpv6Payload{{{{
{values}
}}}};

}}  // namespace {namespace}
"""


def main() -> int:
    args = parse_args()
    try:
        validate_namespace(args.namespace)
        key = read_key(args)
        plaintext = args.input.read_bytes()
        compressed = encode_payload(plaintext, key)
        addresses = to_ipv6(compressed)
        verify(addresses, len(compressed), key, plaintext)
        header = render_header(
            args.input,
            args.namespace,
            addresses,
            len(compressed),
            len(plaintext),
            len(key) * 8,
        )
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(header, encoding="utf-8", newline="\n")
    except (OSError, ValueError, RuntimeError, lzma.LZMAError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(
        f"Generated {args.output}: {len(plaintext)} bytes -> "
        f"{len(compressed)} bytes -> {len(addresses)} IPv6 addresses"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
